# Generated by Django 4.0.6 on 2022-08-02 22:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_perbaikan_detailpasang'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpasang',
            name='alasan_pembatalan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perbaikan',
            name='keterangan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasang',
            name='status',
            field=models.CharField(blank=True, choices=[('Baru', 'Baru'), ('Proses', 'Proses'), ('Selesai', 'Selesai'), ('Batal', 'Batal')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='settingpembayaran',
            name='status',
            field=models.CharField(choices=[('Baru', 'Baru'), ('Belum Lunas', 'Belum Lunas'), ('Lunas', 'Lunas'), ('Kadaluarsa', 'Kadaluarsa'), ('Anda Batalkan', 'Anda Batalkan'), ('Pembayaran Ditolak', 'Pembayaran Ditolak')], max_length=200, null=True),
        ),
    ]
