# Generated by Django 4.0.6 on 2022-08-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_detailpasang_alasan_pembatalan_perbaikan_keterangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpasang',
            name='status',
            field=models.CharField(blank=True, choices=[('Baru', 'Baru'), ('Proses', 'Proses'), ('Bayar', 'Bayar'), ('Selesai', 'Selesai'), ('Batal', 'Batal')], max_length=200, null=True),
        ),
    ]
